- name: Invisibles
  number: 0
  fieldPlayerColors: [red, blue, yellow, black, white, green, orange, purple, brown, gray]
  goalkeeperColors: [blue, yellow, black, white, green, orange, purple, brown, gray, red]
